<a href="https://colab.research.google.com/github/jihyunrue/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [19]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)
df
## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding='utf-8', index=False)

## 5-2 JSON 형식 저장

In [20]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
## DataFrame을 이용한 저장
df = pd.DataFrame([data])
df.to_json('output_df.json', orient='columns', indent=4, force_ascii=False)

## 5-3 Pandas Dataframe 데이터 추출

In [13]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df
## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist())

## DataFrame 값 출력
print(df.values.flatten())

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [14]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [18]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df = pd.DataFrame(data)

## CSV, JSON 형식으로 저장
df.to_csv('students_scores.csv')
df.to_json('students_scores.json')

## HTML 형식으로 저장
html_table = df.to_html()
print(html_table)
with open('students_scores.html', 'w') as f:
    f.write(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터공학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>전자공학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>의학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>심리학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

## 5-6 실습 시나리오

## 데이터 수집

In [22]:
import requests

api_key = '46636548766a696835374349636e68'
url = f"http://openapi.seoul.go.kr:8088/{api_key}/json/energyUseDataSummaryInfo/1/5"


params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'energyUseDataSummaryInfo': {'list_total_count': 1241, 'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'}, 'row': [{'YEAR': '2025', 'MON': '06', 'MM_TYPE': '개인', 'CNT': '1269454', 'EUS': '278745288', 'EUS1': '275851011', 'EUS2': '273151435', 'ECO2_1': '4244065', 'ECO2_2': '2076623.656', 'GUS': '13084768', 'GUS1': '11889039', 'GUS2': '12094650', 'GCO2_1': '1091102', 'GCO2_2': '2182204', 'WUS': '14927683.6', 'WUS1': '15166284.8', 'WUS2': '15371662.2', 'WCO2_1': '-341289.9', 'WCO2_2': '-611822.446', 'HUS': '379182.22', 'HUS1': '368839.049', 'HUS2': '389847.167', 'HCO2_1': '-160.888', 'HCO2_2': '-22448.67848156', 'REG_DATE': '2025-09-01 04:02:15.0'}, {'YEAR': '2025', 'MON': '06', 'MM_TYPE': '학교', 'CNT': '6745', 'EUS': '117808793', 'EUS1': '114793127', 'EUS2': '114623246', 'ECO2_1': '3100606.5', 'ECO2_2': '3096973.668', 'GUS': '2093441', 'GUS1': '2046804', 'GUS2': '2061648', 'GCO2_1': '39207', 'GCO2_2': '78414', 'WUS': '1824338.2', 'WUS1': '1914804.2', 'WUS2': '1956560.2', 'WCO2_1': '-111344', 'WCO2_2': '-333633.134', 'HUS': '8.03', 'HUS1': '8.03', 'HUS2': '8.03', 'HCO2_1': '0', 'HCO2_2': '0', 'REG_DATE': '2025-09-01 04:02:15.0'}, {'YEAR': '2025', 'MON': '06', 'MM_TYPE': '공동주택관리소', 'CNT': '3729', 'EUS': '498863841', 'EUS1': '496003195', 'EUS2': '488758810', 'ECO2_1': '6482838.5', 'ECO2_2': '6482838.5', 'GUS': '2853437', 'GUS1': '2552964', 'GUS2': '2586972', 'GCO2_1': '283460.5', 'GCO2_2': '566921', 'WUS': '20407812.7', 'WUS1': '20616193.4', 'WUS2': '20794568.4', 'WCO2_1': '-297568.2', 'WCO2_2': '-892704.6', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'REG_DATE': '2025-09-01 04:02:15.0'}, {'YEAR': '2025', 'MON': '06', 'MM_TYPE': '종교단체', 'CNT': '849', 'EUS': '6205342', 'EUS1': '6171454', 'EUS2': '6094109', 'ECO2_1': '72560.5', 'ECO2_2': '72560.5', 'GUS': '139336', 'GUS1': '152116', 'GUS2': '141705', 'GCO2_1': '-7575', 'GCO2_2': '-15150', 'WUS': '52228', 'WUS1': '51779', 'WUS2': '49094', 'WCO2_1': '1791.5', 'WCO2_2': '5374.5', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'REG_DATE': '2025-09-01 04:02:15.0'}, {'YEAR': '2025', 'MON': '06', 'MM_TYPE': '소상공인', 'CNT': '53274', 'EUS': '96254029', 'EUS1': '98122772', 'EUS2': '98464917', 'ECO2_1': '-2039815.5', 'ECO2_2': '-2043866.22', 'GUS': '1638563', 'GUS1': '1647690', 'GUS2': '1687480', 'GCO2_1': '-27668', 'GCO2_2': '-55336', 'WUS': '1526737.8', 'WUS1': '1541313.8', 'WUS2': '1576869.2', 'WCO2_1': '-32353.7', 'WCO2_2': '-97437.288', 'HUS': '2', 'HUS1': '2', 'HUS2': '2', 'HCO2_1': '0', 'HCO2_2': '0', 'REG_DATE': '2025-09-01 04:02:15.0'}]}}

## 데이터 프레임 생성

In [42]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['energyUseDataSummaryInfo']['row']
print(type(data))
print(len(data))
print(data[0])
df = pd.DataFrame(data)
print(df.info())
df

<class 'list'>
5
{'YEAR': '2024', 'MON': '12', 'MM_TYPE': '공동주택관리소', 'CNT': '3716', 'EUS': '548480228', 'EUS1': '557799290', 'EUS2': '559693904', 'ECO2_1': '-10266369', 'ECO2_2': '-10266369', 'GUS': '8221238', 'GUS1': '9759209', 'GUS2': '9093999', 'GCO2_1': '-1114991.5', 'GCO2_2': '-2229983', 'WUS': '20262147.7', 'WUS1': '20228097.5', 'WUS2': '20488646.8', 'WCO2_1': '-96224.45', 'WCO2_2': '-288673.35', 'HUS': '0', 'HUS1': '0', 'HUS2': '0', 'HCO2_1': '0', 'HCO2_2': '0', 'REG_DATE': '2025-03-01 04:02:55.0'}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   YEAR      5 non-null      object
 1   MON       5 non-null      object
 2   MM_TYPE   5 non-null      object
 3   CNT       5 non-null      object
 4   EUS       5 non-null      object
 5   EUS1      5 non-null      object
 6   EUS2      5 non-null      object
 7   ECO2_1    5 non-null      object
 8   ECO2_2    5 non-null      object
 9   GUS       5 non-null      object
 10  GUS1      5 non-null      object
 11  GUS2      5 non-null      object
 12  GCO2_1    5 non-null      object
 13  GCO2_2    5 non-null      object
 14  WUS       5 non-null      object
 15  WUS1      5 non-null      object
 16  WUS2      5 non-null      object
 17  WCO2_1    5 non-null      object
 18  WCO2_2    5 non-null      object
 19  HUS       5 non-null      object
 20  HUS1      5 non-null      object
 21  HUS2      5 non-null      object
 22  HCO2_1    5 non-null      object
 23  HCO2_2    5 non-null      object
 24  REG_DATE  5 non-null      object
dtypes: object(25)
memory usage: 1.1+ KB
None

,YEAR,MON,MM_TYPE,CNT,EUS,EUS1,EUS2,ECO2_1,ECO2_2,GUS,...,WUS1,WUS2,WCO2_1,WCO2_2,HUS,HUS1,HUS2,HCO2_1,HCO2_2,REG_DATE
0,2024,12,공동주택관리소,3716,548480228,557799290,559693904,-10266369,-10266369,8221238,...,20228097.5,20488646.8,-96224.45,-288673.35,0,0,0,0,0,2025-03-01 04:02:55.0
1,2024,12,기업,19451,633735769,641412053,669494932,-21717723.5,-21717723.5,30096486,...,4406465.4,4396396.4,47346.5,142039.5,0,0,0,0,0,2025-03-01 04:02:55.0
2,2024,12,개인,1250620,134828126,138280636,138879530,-3751957,-3504709,42103424,...,7440605,7625718.9,-206308.35,-573725.128,1513199.277,1598857.184,1781397.386,-176928.008,-376996.699240516,2025-03-01 04:02:55.0
3,2024,12,공공기관,2459,152992881,161100765,162060905,-8587954,-8587954,3814815,...,854671.2,833317.4,52847.7,158543.1,0,0,0,0,0,2025-03-01 04:02:55.0
4,2024,12,학교,6742,164092999,170867152,169660376,-6170678,-6172770.32,4362563,...,1898794,1939698.4,-60405.2,-181607.796,1062.62,902.03,1220.91,1.15,3.3315,2025-03-01 04:02:55.0

## 다양항 형식으로 데이터 저장

In [29]:
## CSV 형식 데이터 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False)
## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)
## HTML 형식 데이터 저장
df.to_html('air_pollution.html')

In [71]:
import requests
import pandas as pd

def get_year_months():
    year_months = []
    for year in range(2015, 2025):
        for month in range(1, 13):
            year_months.append(f"{year}{month:02d}")
    return year_months

printed_success = False
all_data = []

for year_month in get_year_months():
    year = year_month[:4]
    month = year_month[4:]

    api_key = '46636548766a696835374349636e68'
    url = f"http://openapi.seoul.go.kr:8088/{api_key}/json/energyUseDataSummaryInfo/1/5/{year}/{month}"

    params = {
    'MM_TYPE': '개인'
}
    try:

        response = requests.get(url, params=params)
        response.raise_for_status()

        data = response.json()['energyUseDataSummaryInfo']['row']

        if not printed_success:
            print("API 호출 성공\n")
            printed_success = True
        for values in data:
            if values.get("MM_TYPE") == "개인":
                res = {
                    "MM_TYPE" : values.get("MM_TYPE"),
                    "YEAR": values.get("YEAR"),
                    "MON": values.get("MON"),
                    "EUS": values.get("EUS"),
                    "GUS": values.get("GUS"),
                    "WUS": values.get("WUS"),
                    "HUS": values.get("HUS")
                }
                all_data.append(res)
                ##print(res)

    except requests.exceptions.RequestException as e:
            print(f"API 호출 실패: {e}")
    except json.JSONDecodeError as e:
            print(f"JSON 파싱 실패: {e}")

df = pd.DataFrame(all_data)
print(df.info())
df

API 호출 성공

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MM_TYPE  83 non-null     object
 1   YEAR     83 non-null     object
 2   MON      83 non-null     object
 3   EUS      83 non-null     object
 4   GUS      83 non-null     object
 5   WUS      83 non-null     object
 6   HUS      83 non-null     object
dtypes: object(7)
memory usage: 4.7+ KB
None

   MM_TYPE  YEAR MON        EUS       GUS           WUS           HUS
0       개인  2015  01  193784708  59133720  12819757.886  22740838.937
1       개인  2015  02  189974230  56487358  12656888.218  18793320.213
2       개인  2015  05  177289769  22060892  13086734.214   1320895.801
3       개인  2015  06  186073153  12677645  14241651.402    294312.634
4       개인  2015  07  165114568   8893640  12083879.038    702863.645
..     ...   ...  ..        ...       ...           ...           ...
78      개인  2024  08  463971328   7072251    15873544.6    130082.263
79      개인  2024  09  409872908   5729131    15143321.6   3420507.136
80      개인  2024  10  282268119   8233421    15297669.9   2695491.396
81      개인  2024  11  257927956  17418221    14678672.5   8836296.454
82      개인  2024  12  134828126  42103424     7326853.6   1513199.277

[83 rows x 7 columns]

In [72]:
import requests
import pandas as pd

df = pd.DataFrame(all_data)
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MM_TYPE  83 non-null     object
 1   YEAR     83 non-null     object
 2   MON      83 non-null     object
 3   EUS      83 non-null     object
 4   GUS      83 non-null     object
 5   WUS      83 non-null     object
 6   HUS      83 non-null     object
dtypes: object(7)
memory usage: 4.7+ KB
None

   MM_TYPE  YEAR MON        EUS       GUS           WUS           HUS
0       개인  2015  01  193784708  59133720  12819757.886  22740838.937
1       개인  2015  02  189974230  56487358  12656888.218  18793320.213
2       개인  2015  05  177289769  22060892  13086734.214   1320895.801
3       개인  2015  06  186073153  12677645  14241651.402    294312.634
4       개인  2015  07  165114568   8893640  12083879.038    702863.645
..     ...   ...  ..        ...       ...           ...           ...
78      개인  2024  08  463971328   7072251    15873544.6    130082.263
79      개인  2024  09  409872908   5729131    15143321.6   3420507.136
80      개인  2024  10  282268119   8233421    15297669.9   2695491.396
81      개인  2024  11  257927956  17418221    14678672.5   8836296.454
82      개인  2024  12  134828126  42103424     7326853.6   1513199.277

[83 rows x 7 columns]